DECODING WHAT WE CODED IN THE LAST ONE

In [3]:
import pickle
import numpy as np

In [5]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl' ,'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl' , 'rb'))
clf = pickle.load(open('models/clf.pkl' , 'rb'))

In [6]:
#Assume user input
#Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male' ,31.0 , 0,0,10.5 , 'S'], dtype = object).reshape(1,7)

In [7]:
test_input


array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [8]:
test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1,1))


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [11]:
test_input_sex

array([[0., 1.]])

In [10]:
test_input_embarked =ohe_embarked.transform(test_input[: ,-1].reshape(1,1))

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [12]:
test_input_embarked


array([[0., 0., 1., 0.]])