In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer,MissingIndicator

In [3]:
df = pd.read_csv('titanic_train.csv' , usecols = ['Age' , 'Fare' , 'Survived'])


In [4]:
df.sample(10)

,Survived,Age,Fare
824,0,2.0,39.6875
453,1,49.0,89.1042
352,0,15.0,7.2292
356,1,22.0,55.0000
799,0,30.0,24.1500
544,0,50.0,106.4250
503,0,37.0,9.5875
531,0,NaN,7.2292
43,1,3.0,41.5792
506,1,33.0,26.0000


In [5]:
x = df.drop(columns = ['Survived'])
y = df['Survived']

In [6]:
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size = 0.2, random_state = 2)

In [7]:
x_train.head()


,Age,Fare
30,40.0,27.7208
10,4.0,16.7000
873,47.0,9.0000
182,9.0,31.3875
876,20.0,9.8458


In [21]:
si = SimpleImputer()
#missing values got replaced by mean values using simple imputer
x_train_trf = si.fit_transform(x_train)
x_test_trf = si.transform(x_test)

In [60]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf , y_train)
y_pred = clf.predict(x_test_trf)



In [13]:
x_train_trf

array([[ 40.        ,  27.7208    ],
       [  4.        ,  16.7       ],
       [ 47.        ,   9.        ],
       ...,
       [ 71.        ,  49.5042    ],
       [ 29.78590426, 221.7792    ],
       [ 29.78590426,  25.925     ]], shape=(712, 2))

In [14]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

In [19]:
y_pred.shape

(179,)

In [17]:
y_test.shape

(179,)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.6145251396648045

In [ ]:
#with missing indicator

In [ ]:
from sklearn.linear_model import LogisticRegression



In [22]:
mi = MissingIndicator()
clf = LogisticRegression()

x_train_trf2 = mi.fit_transform(x_train)
x_test_trf2 = mi.transform(x_test)



In [30]:
x_train_trf2


array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [32]:
x_train['Age_na'] = x_train_trf2
x_train.sample(10)


,Age,Fare,Age_na
545,64.00,26.0000,False
796,49.00,25.9292,False
806,39.00,0.0000,False
277,NaN,0.0000,True
598,NaN,7.2250,True
224,38.00,90.0000,False
14,14.00,7.8542,False
802,11.00,120.0000,False
755,0.67,14.5000,False
778,NaN,7.7375,True


In [ ]:
#the above data form is what missing inidcator does . rest of the process is same

In [33]:
x_test_trf2

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [55]:
x_test['Age_na'] = x_test_trf2

In [65]:
x_test_trf2


array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75   

In [67]:
x_test.sample(10)


,Age,Fare,Age_na
743,24.0,16.1000,0.0
109,NaN,24.1500,1.0
382,32.0,7.9250,0.0
272,41.0,19.5000,0.0
702,18.0,14.4542,0.0
386,1.0,46.9000,0.0
67,19.0,8.1583,0.0
652,21.0,8.4333,0.0
68,17.0,7.9250,0.0
786,18.0,7.4958,0.0


In [59]:
si = SimpleImputer() #to fill the missing values in the age column

x_train_trf2 = si.fit_transform(x_train)
x_test_trf2 = si.transform(x_test)

In [61]:
clf = LogisticRegression()
clf.fit(x_train_trf2 , y_train)
y_pred2 = clf.predict(x_test_trf2)

In [62]:
accuracy_score(y_test, y_pred2)


0.6312849162011173

In [63]:
x_test_trf2


array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75   