In [165]:
from sklearn.datasets import load_diabetes

In [166]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [167]:
x, y = load_diabetes(return_X_y = True)

In [168]:
print(x.shape)
print(y.shape)

(442, 10)
(442,)


In [169]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 2)

In [170]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [171]:
lr.fit(x_train , y_train)
y_pred = lr.predict(x_test)

In [172]:
print(lr.coef_)
print(lr.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [173]:
from sklearn.metrics import r2_score
r2_score(y_test , y_pred)

0.4399338661568968

In [174]:
x_test

array([[ 0.06713621, -0.04464164,  0.00349435,  0.03564379,  0.0493413 ,
         0.03125356,  0.07072993, -0.03949338, -0.00061174,  0.01963284],
       [-0.07816532,  0.05068012,  0.07786339,  0.05285804,  0.07823631,
         0.0644473 ,  0.02655027, -0.00259226,  0.04067283, -0.00936191],
       [ 0.04170844,  0.05068012, -0.01482845, -0.01713512, -0.00569682,
         0.00839372, -0.01394774, -0.00185424, -0.01189685,  0.00306441],
       [-0.04547248, -0.04464164, -0.04824063, -0.01944183, -0.00019301,
        -0.01603186,  0.06704829, -0.03949338, -0.02479543,  0.01963284],
       [ 0.0090156 ,  0.05068012,  0.06924089,  0.05974375,  0.01769438,
        -0.02323427, -0.04708248,  0.03430886,  0.10329702,  0.07348023],
       [ 0.03444337,  0.05068012,  0.12528712,  0.02875809, -0.05385517,
        -0.01290037, -0.10230705,  0.1081111 ,  0.00027248,  0.02791705],
       [-0.03457486, -0.04464164, -0.05901875,  0.00121528, -0.05385517,
        -0.07803525,  0.06704829, -0.0763945 

In [175]:
class GDregressor :
    def __init__ (self , epochs = 100 , LR = 0.01):
        self.coef_= None 
        self.intercept_ = None
        self.LR = LR
        self.epochs = epochs 

    def fit(self , x_train , y_train):
        #initialise your coefs and intercept 

        self.intercept_  = 0 
        self.coef_ = np.ones(x_train.shape[1])

        for i in range(self.epochs):
                #update all the coefs and intercept 
                y_pred = self.intercept_ + np.dot(x_train ,self.coef_ )
                intercept_derv = - 2 * (np.mean(y_train - y_pred))
                coef_derv = -2 * np.dot( (y_train - y_pred) , x_train )/x_train.shape[0]
                self.intercept_ = self.intercept_ - (self.LR * intercept_derv)
                self.coef_ = self.coef_ - (self.LR * coef_derv)

          
        return(self.intercept_ , self.coef_)
       



    def predict(self , x_test):
        return np.dot(x_test , self.coef_) + self.intercept_

In [176]:
gd = GDregressor(epochs = 100000, LR = 0.001)

In [177]:
gd.fit(x_train , y_train)

(np.float64(151.93993056681023),
 array([  62.25237667,  -24.14858069,  262.33934178,  192.15720081,
          39.46662262,   10.25158698, -142.4629384 ,  124.289042  ,
         244.27466156,  119.30148538]))

In [178]:
y_pred1 = gd.predict(x_test)
y_pred1

array([154.43880934, 184.89602596, 145.20708442, 115.44876358,
       226.35313888, 220.40543547, 110.26555373, 118.35587783,
        98.58683011, 180.37530096, 165.05755913, 169.61428324,
       181.94949665, 156.687341  , 228.93854176, 102.03387585,
       176.63877187, 136.89033288, 143.91666679, 143.42634428,
       128.81672035, 193.11292167, 170.73135272, 176.6755978 ,
       129.24368508, 211.04582531, 187.37754881, 132.18810433,
        77.09875959, 232.55444442, 224.57795199, 125.53030991,
        86.7479992 , 120.61289723, 192.43837438, 165.84302906,
       167.33398583, 192.66721984, 120.54913481, 221.10368207,
       135.45358059, 132.11775898, 181.42571371, 182.0917241 ,
       166.34037179, 148.09376448, 172.01300284, 255.53984837,
       125.70870242, 192.48538336, 219.38137014, 128.28754304,
       141.5805709 , 159.41387531, 184.37663319, 124.59049746,
       164.98381875,  97.45542733, 157.59817266, 140.38631526,
       162.7076443 , 172.96803278, 119.11236408, 191.33

In [179]:
x_train.shape[1] #that is we have 10 coeff since we have 10 columns 

10